hydra:
  run:
    dir: .

# Set to true for federated learning mode
federated: false
secured: false

model:
  name: "hard_sharing" # Change this to the appropriate model name
  params:
    hf_input_dim: 3 # Adjust this based on your dataset
    lf_input_dim: 1
    lf_output_dim: 1
    hidden_dim: 64
    num_layers: 2
    dropout: 0.2

trainer:
  name: "normal_trainer" # Change this to the appropriate trainer name
  params:
    learning_rate: 0.001
    grad_clip: 1.0
    device: "cpu"
    # --- ONLY for ts_diff ---
    time_emb_dim: 128
    # --- ONLY for federated learning ---
    personalization_lr: 0.00005
    local_epochs: 20
    personalization_epochs: 10
    meta_learning_rate: 0.01
    # --- ONLY for secured federated learning ---
    noise_scale: 0.1
    clip_norm: 1.0
    encoder_noise_scale: 0.05
    enable_secure_agg: true

# ──────────────────────────────────────────────
# DIFFUSION: only used when model.name == "ts_diff"
# ──────────────────────────────────────────────
diffusion:
  num_timesteps: 100
  beta_start: 1e-4
  beta_end: 0.1

train:
  epochs: 30
  eval_horizons: [1, 2, 4, 8, 16] # only used by ts_diff

data:
  base_path: "src/TS_MTL/data/air_quality"
  sites: [station-1, station-2, station-3, station-4, station-5, station-6]
  hf_suffix: "-hf.csv"
  lf_suffix: "-lf.csv"
  features: ["PM2.5", "NO2", "PM10"]
  target: ["CO"]
  min_date: "2014-09-01"
  max_date: "2014-11-12"
  hf_lookback: 64
  lf_lookback: 32
  forecast_horizon: 1
  freq_ratio: 2
  batch_size: 16
  train_ratio: 0.8
